name: Build and deploy JAR app to Azure Web App - springmall2

on:
  push:
    branches:
      - '*' # 모든 브랜치에서 트리거 (빌드 및 테스트)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # ✅ 이 단계에서 테스트 + 커버리지 생성
      - name: Run tests and generate JaCoCo report
        run: ./gradlew clean build jacocoTestReport

      - name: List contents of build/libs
        run: ls -alR build/libs  # 빌드 디렉토리 내용 출력

      # ✅ Codecov 에 결과 업로드
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: yunok96/springmall2-v2
          files: build/reports/jacoco/test/jacocoTestReport.xml

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/build/libs/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' # 배포는 master나 main 브랜치에서만 실행

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: List files after artifact download
        run: ls -alR

      - name: Print current working directory
        run: pwd

      - name: List everything
        run: find . -type f

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'springmall2'
          slot-name: 'Production'
          package: '*.jar'
          startup-command: 'java -jar -Dspring.profiles.active=prod /home/site/wwwroot/springmall2.jar'
